# Generated by Django 3.1.12 on 2021-06-09 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survival_guide', '0002_sectionimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionimage',
            name='caption',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
