# Generated by Django 3.1.12 on 2021-06-09 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survival_guide', '0003_sectionimage_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionimage',
            name='page',
        ),
        migrations.AddField(
            model_name='section',
            name='image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='survival_guide.sectionimage'),
            preserve_default=False,
        ),
    ]
