# Generated by Django 3.1.12 on 2021-06-09 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('survival_guide', '0005_auto_20210609_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='wagtailimages.image'),
        ),
    ]
